# Generated by Django 4.2.4 on 2023-08-18 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_vendorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='contract',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
