# Generated by Django 3.2.20 on 2023-08-19 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_vendorprofile_contract_user_contract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorprofile',
            name='max_purchases',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vendorprofile',
            name='vendor_tier',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
