# Generated by Django 3.2.20 on 2023-08-19 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_tier', models.PositiveIntegerField(blank=True, null=True)),
                ('max_purchases', models.PositiveIntegerField(blank=True, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=225)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('instock', models.IntegerField(default=0)),
                ('product_img', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='image/')),
                ('category', models.CharField(blank=True, choices=[('Elec', 'Electronics'), ('MCol', "Men's Fashion"), ('FCol', "Women's Fashion")], max_length=100, null=True)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.vendorprofile')),
            ],
        ),
    ]
