# Generated by Django 3.2.20 on 2023-08-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='price_tokens',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
