# Generated by Django 3.2.20 on 2023-08-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_usercoupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorprofile',
            name='weighted_avg',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
